### ISSUE TITLE
epidiff.systems.i2mv_system.I2MVSystem

### ISSUE THREAD

**Issue by Mrguanglei** [huanngzh/EpiDiff#9]
There was an error when doing the single card training, about：

Global seed set to 42
[rank: 0] 
Traceback (most recent call last):
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'epidiff.systems' has no attribute 'i2mv_system'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/root/miniconda3/envs/ep/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/autodl-tmp/EpiDiff/epidiff/systems/i2mv_system.py", line 8, in <module>
    from diffusers import AutoencoderKL, DDIMScheduler, UNet2DConditionModel
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/diffusers/utils/__init__.py", line 21, in <module>
    from .constants import (
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/diffusers/utils/constants.py", line 17, in <module>
    from huggingface_hub.constants import HF_HOME
ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (/root/miniconda3/envs/ep/lib/python3.9/site-packages/huggingface_hub/constants.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/hydra/_internal/utils.py", line 658, in _locate
    raise ImportError(
ImportError: Error loading 'epidiff.systems.i2mv_system.I2MVSystem':
ImportError("cannot import name 'HF_HOME' from 'huggingface_hub.constants' (/root/miniconda3/envs/ep/lib/python3.9/site-packages/huggingface_hub/constants.py)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/autodl-tmp/EpiDiff/epidiff/utils/misc.py", line 165, in wrap
    task_func(cfg, config_path=config_path)
  File "/root/autodl-tmp/EpiDiff/train.py", line 64, in train
    model: LightningModule = hydra.utils.instantiate(cfg.system)
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'epidiff.systems.i2mv_system.I2MVSystem', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: system
Traceback (most recent call last):
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'epidiff.systems' has no attribute 'i2mv_system'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/root/miniconda3/envs/ep/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/autodl-tmp/EpiDiff/epidiff/systems/i2mv_system.py", line 8, in <module>
    from diffusers import AutoencoderKL, DDIMScheduler, UNet2DConditionModel
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/diffusers/utils/__init__.py", line 21, in <module>
    from .constants import (
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/diffusers/utils/constants.py", line 17, in <module>
    from huggingface_hub.constants import HF_HOME
ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (/root/miniconda3/envs/ep/lib/python3.9/site-packages/huggingface_hub/constants.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/hydra/_internal/utils.py", line 658, in _locate
    raise ImportError(
ImportError: Error loading 'epidiff.systems.i2mv_system.I2MVSystem':
ImportError("cannot import name 'HF_HOME' from 'huggingface_hub.constants' (/root/miniconda3/envs/ep/lib/python3.9/site-packages/huggingface_hub/constants.py)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/autodl-tmp/EpiDiff/train.py", line 138, in <module>
    main(args, extras)
  File "/root/autodl-tmp/EpiDiff/train.py", line 130, in main
    train(cfg, args.config)
  File "/root/autodl-tmp/EpiDiff/epidiff/utils/misc.py", line 175, in wrap
    raise ex
  File "/root/autodl-tmp/EpiDiff/epidiff/utils/misc.py", line 165, in wrap
    task_func(cfg, config_path=config_path)
  File "/root/autodl-tmp/EpiDiff/train.py", line 64, in train
    model: LightningModule = hydra.utils.instantiate(cfg.system)
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/root/miniconda3/envs/ep/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'epidiff.systems.i2mv_system.I2MVSystem', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: system

How can I fix this

**Comment by huanngzh** [comment]
Maybe try the solution proposed in [this issue](https://github.com/huggingface/alignment-handbook/issues/94#issuecomment-1883119335).

**Comment by buyu-aigc** [comment]
Global seed set to 0
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1061, in _validate_conn
    conn.connect()
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f6775b78d60>, 'Connection to huggingface.co timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /ashawkey/stable-zero123-diffusers/resolve/main/unet/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6775b78d60>, 'Connection to huggingface.co timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1247, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1624, in get_hf_file_metadata
    r = _request_wrapper(
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 402, in _request_wrapper
    response = _request_wrapper(
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 425, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /ashawkey/stable-zero123-diffusers/resolve/main/unet/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6775b78d60>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: e00d4170-3ad1-4e47-b29a-732be591dc6f)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 370, in load_config
    config_file = hf_hub_download(
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1377, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/mjc/EpiDiff/epidiff/systems/i2mv_system.py", line 63, in __init__
    unet = UNet2DConditionModel.from_pretrained(
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 528, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 397, in load_config
    raise EnvironmentError(
OSError: ashawkey/stable-zero123-diffusers does not appear to have a file named config.json.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "inference.py", line 141, in <module>
    main()
  File "inference.py", line 107, in main
    model: LightningModule = hydra.utils.instantiate(cfg.system)
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/usr/local/anaconda3/envs/mjc_epidiff/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'epidiff.systems.i2mv_system.I2MVSystem':
OSError('ashawkey/stable-zero123-diffusers does not appear to have a file named config.json.')
full_key: system


Successfully installed huggingface-hub-0.19.2
大佬，咋办呢？

**Comment by chenhui-hub** [comment]
请问一下解决了吗
